### ISSUE TITLE
ruby-oo-self-person-lab

### ISSUE THREAD

**Issue by Hieuhuule** [learn-co-curriculum/ruby-oo-self-person-lab#7]
### Canvas Link

https://learning.flatironschool.com/courses/1879/assignments/125249?module_item_id=259117

### Concern

This assignment couldn't be completed without using "self." which is not taught until the next module. Only using "@" was not workable as they are not always interchangeable.

### Additional Context

Specifically ran into problems with the #take_bath, #work_out, #call_friend before I finally started using "self."

**Comment by lizbur10** [comment]
Thanks for bringing this to our attention @Hieuhuule ! This lab has been moved into the Self in Ruby module. 💙
